package com.miaosha.dao;

import com.miaosha.dataobject.UserPwdDO;

public interface UserPwdDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Oct 10 23:11:50 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Oct 10 23:11:50 GMT+08:00 2020
     */
    int insert(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Oct 10 23:11:50 GMT+08:00 2020
     */
    int insertSelective(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Oct 10 23:11:50 GMT+08:00 2020
     */
    UserPwdDO selectByPrimaryKey(Integer id);

    /**
     * 通过user_id查询实体
     * @param userId
     * @return
     */
    UserPwdDO selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Oct 10 23:11:50 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Oct 10 23:11:50 GMT+08:00 2020
     */
    int updateByPrimaryKey(UserPwdDO record);
}